Sprint 3/step 1
LessiaVK/react-burger pull request #4
Opened 2023-03-19 19:49 UTC by LessiaVK

2023-03-19 21:15 UTC, andryxxa93 requested changes
Здравствуйте! Хорошая работа 👍 
Что понравилось:
- Реализована защита приватных и публичных роутов
- Есть механизм обновления токена
- Используются статичные селекторы

Что необходимо исправить:
- Если токена нет, то не нужно и пытаться его обновить.

<img width="1439" alt="Снимок экрана 2023-03-19 в 23 56 01" src="https://user-images.githubusercontent.com/60173362/226208436-f5d9b60f-ea70-4a67-adbf-9fce18c90225.png">

- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут /`login`. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью  return` <Redirect to={location?.state?.from || '/'} />; `(эти данные записываются в `ProtectedRoute`, а используются в `Login` для `Redirect`)

- ProtectedRoute должен использовать  Redirect с параметрами для универсального возращения пользователя обратно туда, куда он хотел попасть.

- При клике по ингредиенту  должен происходить переход на маршрут `/ingredients/:id` и открываться модальное окно с описанием ингредиента. При прямом переходе на этот маршрут открываться должна страница с информацией об ингредиенте.

- Необходимо использовать не `onClick` событие `div` как ссылку, а компонент `Link.`
- Если есть инпуты, то они должны быть внутри тега `form`, и на этот тег form нужно навешивать обработчик `onSubmit`, а не обработчик `onClick` на кнопку сабмита.

- После обновления токена необходимо повторить запрос, который не был выполнен успешно, но с уже свежим токеном. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.

**Можно лучше**
- Ответом на запрос регистрации сервер даёт токены - это значит, что вы можете сразу авторизовать юзера.
- Чтобы приходящий с сервера токен заносился всегда по пути "/" в куку, нужно в функцию setCookies передавать как значение параметра props аргумент {path="/"}:
setCookie('name', value, { path: '/' }).
Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
Уничтожать токен при логауте пользователя нужно также по пути path: '/'.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-19 21:15 UTC, andryxxa93 commented on src/components/app/App.js
> +            <Route path="/ingredients/:id" element={<IngredientPage />}></Route>
**Необходимо исправить**
Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://reactrouter.com/web/example/modal-gallery . Пожалуйста, посоветуйтесь с наставником.

2023-03-19 21:15 UTC, andryxxa93 commented on src/components/app/App.js
> +              path="/register"
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-19 21:15 UTC, andryxxa93 commented on src/pages/ForgotPasswordPage.js
> +const codeRequest = async (form, navigate) => {
**Можно лучше**
Запросы лучше держать в отдельном файле

2023-03-19 21:15 UTC, andryxxa93 commented on src/pages/ForgotPasswordPage.js
> +    setCookie("forgot", "1");
**Можно лучше**
Для такой информации вполне подойдёт redux стор.

2023-03-19 21:15 UTC, andryxxa93 commented on src/components/app-header/AppHeader.js
> +            <div
**Необходимо исправить**
Необходимо использовать не `onClick` событие `div` а компонент `Link`.

2023-03-19 21:15 UTC, andryxxa93 commented on src/components/protected-route-element/ProtectedRouteLogins.js
> +export const ProtectedRouteLogins = ({ element }) => {
**Можно лучше**

Чтобы не дублировать практически одинаковую логику - доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-03-22 08:53 UTC, andryxxa93 commented
- Перестал обновляться токен. 
<img width="1435" alt="Снимок экрана 2023-03-22 в 11 51 51" src="https://user-images.githubusercontent.com/60173362/226849963-d815b156-72f0-4e67-8d2c-0dd7687f5eff.png">

2023-03-22 10:44 UTC, LessiaVK commented
Андрей, добрый день!

2023-03-22 11:02 UTC, LessiaVK commented
Я залогинилась. Подождала пока токен закончился.
![01](https://user-images.githubusercontent.com/50830097/226884225-8d9a5ca4-9a0e-430d-a27b-597b59eee234.jpeg)

2023-03-22 11:02 UTC, LessiaVK commented
Нажала кнопку сохранить. Обращение к серверу произошло.
![02](https://user-images.githubusercontent.com/50830097/226884343-a66f947d-e347-4079-984f-abff4d4d2575.jpeg)

2023-03-22 11:03 UTC, LessiaVK commented
Токен обновился
![03](https://user-images.githubusercontent.com/50830097/226884634-259553b4-5478-4e91-8da7-8c9e419cdf50.jpeg)

2023-03-22 12:05 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-31 21:45 UTC, merged