Sprint 5/step 1
LessiaVK/react-burger pull request #6
Opened 2023-04-28 01:58 UTC by LessiaVK

2023-04-28 05:42 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;
- Теперь пользователь может посмотреть историю заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- При запуске проекта возникают ошибки: <https://disk.yandex.com/i/4nHNFq8z3zF67w>;

- <https://disk.yandex.com/i/tDdhqT3p3iReMg> - Нужно выровнять хедер;

- При открытии/закрытии модального окна на странице `/feed`, у вас происходит открытие/закрытие сокет соединения `WS /all`. Это не очень хорошо, нужно чтобы сокет-соединение открывалось только 1 раз, при посещении страницы `/feed`. Перед отправкой работы, проверьте это поведение на модальном окне `/profile/orders`, там тоже сокет-соединение должно срабатывать только 1 раз, и только при открытии страницы.

- При открытии/закрытии модального окна на странице `/ingredients`, у вас происходит запрос `GET /ingredients`. Это не очень хорошо, нужно чтобы запрос выполнялся только 1 раз, при загрузке приложения в `app`.

- У ссылок не должно быть подчёркиваний: <https://disk.yandex.com/i/tylsVJmx0jEkcA>;

- <https://disk.yandex.com/i/qKh-Cz3g2DOwwA> - Если пользователь отредактировал данные в форме, то появляются кнопки "Отмена" и "Сохранить". Кнопки не должны отображаться всегда;

- Если нажать на карточки заказов, то открывается модальное окно `/feed`, а не `/profile/orders`. А также при открытии возникает ошибка, и приложение падает. <https://disk.yandex.com/i/1CkF2-M12vgf3A>;

- Если перезагрузить страницу на роуте `/profile/* - все роуты связанные /profile`, то пользователь попадает на главную страницу, а должен был остаться на той странице. Вообщем, пользователя (авторизированного) не должно перенаправлять на другие страницы, со страниц профиля, при перезагрузке. Вам нужно дождаться пока сервер выполнит запрос на получения пользователя, и только потом делать проверку.

- <https://disk.yandex.com/i/7oqXKx-xRg14gA> - Если открыть адрес `/feed/:id` в новом окне, то у вас не отображается заказ;

- При открытии страницы `/feed` и `/profile/orders` у вас происходит очень много запросов `GET /ingredients`, это нужно исправить, запрос должен происходить только 1 раз в компоненте `app` <https://disk.yandex.com/i/eXgT22wY4Q1fxw>;

- Магические значения нужно вынести в константы. Магическими называют такие числа в коде, смысл которых понятен только написавшему их программисту. Константы принято записывать в `UPPER_CASE`;

### **Не удалось проверить:**

- Функционал с `profile/orders/:id`, не удалось проверить, т.к. при открытии модального окна возникает ошибка.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-04-28 05:42 UTC, ArslanDev666 commented on src/components/order-feed/OrderFeed.tsx
> +};
**Можно лучше:**

неиспользуемые данные лучше удалить.

2023-04-28 05:42 UTC, ArslanDev666 commented on src/components/order-feed/OrderFeed.tsx
> +};
**Надо исправить:**

Тип ингредиента много где повторяется, нужно его переиспользовать, а не писать каждый раз заново.

2023-04-28 05:42 UTC, ArslanDev666 commented on src/components/order-feed/OrderFeed.tsx
> +  keyIndex: any;
**Надо исправить:**

тут не должно быть `any`.

2023-04-28 05:42 UTC, ArslanDev666 commented on src/components/order-feed/OrderFeed.tsx
> +  });
**Надо исправить:**

Цену и остальные вычисления, нужно делать через `useMemo`, а не просто внутри кода, иначе у вас каждый ререндер будут эти вычисления происходить, а также возможны ошибки в рендере, т.к. изменения обычных переменных не вызывают ререндер.

2023-04-28 05:42 UTC, ArslanDev666 commented on src/components/order-feed/OrderFeed.tsx
> +          const n: Number = 150 - Number(index);
**надо исправить:**

Магические числа, нужно вынести в константу.

2023-04-28 05:42 UTC, ArslanDev666 commented on src/components/order-feed/OrderFeed.tsx
> +  }, []);
**Надо исправить:**

Не совсем понимаю, зачем тут `dispatch(getIngredients());`

2023-04-28 05:42 UTC, ArslanDev666 commented on src/components/order-feed/OrderFeedBoard.tsx
> +  }
**Надо исправить:**

тут лучше использовать `useMemo`

2023-04-28 05:42 UTC, ArslanDev666 commented on src/components/order-feed/OrderFeedBoard.tsx
> +                  if (index < 10) {
**Надо исправить:**

Здесь и далее.

Магические значение нужно вынести в константу.

2023-04-28 05:42 UTC, ArslanDev666 commented on src/components/order-feed/OrderFeedDetails.tsx
> +const ListIngredients = (props: any) => {
**Надо исправить:**

Тут должно быть описание пропсов, а не тип `any`

2023-04-28 05:42 UTC, ArslanDev666 commented on src/components/order-feed/OrderFeedDetails.tsx
> +  }
**Надо исправить:**

Тут лучше использовать `useMemo`.

А также не совсем понимаю зачем вам тут массив, если можно обойтись объектом.

2023-04-28 05:42 UTC, ArslanDev666 commented on src/components/protected-route-element/ProtectedRouteLogins.tsx
> +export const ProtectedRouteLogins = (props: any) => {
**Надо исправить:**

Нужно полное описание пропсов, а не тип `any`

2023-04-28 05:42 UTC, ArslanDev666 commented on src/pages/ProfileOrdersPage.tsx
> +  }, []);
**надо исправить:**

Логика защиты роутов и т.п. должны находиться в  компоненте `protect-route`, вам не нужно дополнительно что-то проверять.

Обновление токена должно происходить в самих запросах и только в том случае, если токен истёк. 

Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.
Обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке

Для этого используйте обертку над fetch, примерно такую

```js
// например вот так
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkResponse(res);
  } catch (err) {
    if (err.message === 'jwt expired') {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem('refreshToken', refreshData.refreshToken);
      setCookie('accessToken', refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkResponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-04-28 05:42 UTC, ArslanDev666 commented on src/pages/orderPage.tsx
> +  }, []);
**Надо исправить:**

Тут не должно быть этого запроса.

2023-04-28 05:42 UTC, ArslanDev666 commented on src/services/actions/actionTypes.ts
> +export const FETCH_INGREDIENTS: 'FETCH_INGREDIENTS' = "FETCH_INGREDIENTS";
**Можно лучше:**

Не стоит явно указывать тип у простых констант, ведь константы, по умолчанию имеют тип равный её значению.

2023-04-28 05:42 UTC, ArslanDev666 commented on src/services/initialState.ts
> +    currentIngredient: undefined,
**Надо исправить:**

Если значения нет, то нужно использовать null, а не undefined.

2023-04-28 05:42 UTC, ArslanDev666 commented on src/services/initialState.ts
>      currentOrder: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-04-28 05:42 UTC, ArslanDev666 commented on src/services/initialState.ts
> +    orders: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-05-01 03:37 UTC, LessiaVK commented on src/components/order-feed/OrderFeed.tsx
> +};
Простите, не поняла вопрос: проверила всё, он определяется только один раз, дальше используется.

2023-05-01 04:51 UTC, ArslanDev666 commented on src/components/order-feed/OrderFeed.tsx
> +};
Да, что-то я  не о том подумал)) тут всё ок с типом. Можете пропустить этот комментарий

2023-05-02 13:33 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но всё ещё есть несколько замечаний, которые нужно исправить:**

- Теперь при открытии модального окна `/feed/:id` и `/profile/orders/:id` у вас закрывается сокет-соединение, этого не должно происходить, сокет-соединение остаётся открытым, пока пользователь не покинет страницу.

- При нажатии на кнопку отмены, у не сбрасывается поле пароля. <https://disk.yandex.com/i/cTNLKOmXtPypFg>;

- не исправлено замечание, если у вас возникли сложности, советую обратиться к наставнику:

  - <https://github.com/LessiaVK/react-burger/pull/6#discussion_r1179948386>
  - <https://github.com/LessiaVK/react-burger/pull/6#discussion_r1179949733>
  - <https://github.com/LessiaVK/react-burger/pull/6#discussion_r1179949840>

2023-05-02 13:33 UTC, ArslanDev666 commented on src/components/order-feed/OrderFeedDetails.tsx
> +  });
**Можно лучше:**

лучше написать вот так: 

```js
  const listIngrsCount = listIngrs.reduce<FeedIngredientType>((acc, item) => {
    if (!item) return acc;

    if (acc[item._id]) {
      acc[item._id].count += 1;
    } else {
      acc[item._id] = { ...item, count: 1 };
    }

    return acc;
  }, {});
```

2023-05-03 14:26 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-05-03 14:26 UTC, ArslanDev666 commented on src/components/app-header/AppHeader.tsx
> +              dispatch({ type: wsActions.wsClose });
**Можно лучше:**

Здесь и далее.

вы должны вызывать закрытие экшена, при размонтировании компонента. А не при клике на ссылку.
А также используйте компонент `link` из `react-router-dom`

2023-05-03 17:46 UTC, merged